<div class="share-box">
  <div id="ember863" class="artdeco-modal__header ember-view">
      <div class="display-flex align-items-center">
        <h2 id="share-to-linkedin-modal__header" tabindex="-1">
          
              Create a poll
            
        </h2>
      </div>

</div>
  <div id="ember864" class="artdeco-modal__content p0 ember-view">
    
              
    <div class="full-height">
      <form class="share-box-modal-content__container pv3 ph5">
        <div class="mb4">
          <div id="ember865" class="artdeco-text-input artdeco-text-input--type-multiline artdeco-text-input--color-default artdeco-text-input--state-required ember-view"><!---->  <div id="ember866" class="ember-view">  <label class="artdeco-text-input--label" for="input-uid-ember865">Your question</label>
<textarea class="polls-detour__form-fields polls-detour__question-field artdeco-text-input--input artdeco-text-input__textarea" required="" placeholder="E.g., How do you commute to work?" aria-describedby=" ember865-char-limit" id="input-uid-ember865"></textarea></div>
  <p class="artdeco-text-input--helper-box">
   <span class="artdeco-text-input--counter" aria-live="polite" aria-atomic="true">0/140</span>
      <span class="a11y-text" id="ember865-char-limit">140 maximum characters allowed.</span>
  </p>
</div>
        </div>
          <div class="mb3">
            <div>
              <label for="poll-option-1" class="polls-detour__input-label polls-detour__required-input-indicator">Option 1</label>
<!---->            </div>
            <div id="ember867" class="artdeco-text-input artdeco-text-input--type-text artdeco-text-input--color-default artdeco-text-input--state-required ember-view">  <div id="ember868" class="artdeco-text-input--container ember-view"><!---->  <input class="polls-detour__form-fields artdeco-text-input--input" id="poll-option-1" required="" placeholder="E.g., Public transportation" aria-describedby=" ember867-char-limit" type="text">
</div>
<!---->  <p class="artdeco-text-input--helper-box">
<!---->      <span class="artdeco-text-input--counter" aria-live="polite" aria-atomic="true">0/30</span>
      <span class="a11y-text" id="ember867-char-limit">30 maximum characters allowed.</span>
  </p>
</div>
          </div>
          <div class="mb3">
            <div>
              <label for="poll-option-2" class="polls-detour__input-label polls-detour__required-input-indicator">Option 2</label>
<!---->            </div>
            <div id="ember869" class="artdeco-text-input artdeco-text-input--type-text artdeco-text-input--color-default artdeco-text-input--state-required ember-view">  <div id="ember870" class="artdeco-text-input--container ember-view"><!---->  <input class="polls-detour__form-fields artdeco-text-input--input" id="poll-option-2" required="" placeholder="E.g., Drive myself" aria-describedby=" ember869-char-limit" type="text">
</div>
<!---->  <p class="artdeco-text-input--helper-box">
<!---->      <span class="artdeco-text-input--counter" aria-live="polite" aria-atomic="true">0/30</span>
      <span class="a11y-text" id="ember869-char-limit">30 maximum characters allowed.</span>
  </p>
</div>
          </div>

          <div class="mb3">
            <button id="ember871" class="artdeco-button artdeco-button--2 artdeco-button--secondary ember-view" type="button">        <svg role="none" aria-hidden="true" class="artdeco-button__icon " xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" data-supported-dps="16x16" data-test-icon="add-small">
<!---->    

    <use href="#add-small" width="16" height="16"></use>
</svg>


<span class="artdeco-button__text">
    Add option
</span></button>
          </div>

        <h3 id="polls-duration-label" class="t-14 t-black t-bold mb3">Poll duration</h3>

        <select aria-labelledby="polls-duration-label" class="mb4">
          <option value="1">1 day</option>
          <option value="3">3 days</option>
          <option value="7">1 week</option>
          <option value="14">2 weeks</option>
        </select>
        <p class="mb3 t-14 t-black">We don’t allow requests for political opinions, medical information or other sensitive data.</p>
      </form>

      

    <div class="share-box-footer
        ">
<!---->      <div class="share-box-footer__main-actions">
          <button id="ember872" class="artdeco-button artdeco-button--2 artdeco-button--secondary ember-view" type="button"><!---->
<span class="artdeco-button__text">
    Back
</span></button>
          <button disabled="" id="ember873" class="share-box-footer__primary-btn artdeco-button artdeco-button--2 artdeco-button--primary artdeco-button--disabled ember-view" type="button"><!---->
<span class="artdeco-button__text">
    
              Done
          
</span></button>
      </div>
    </div>
  
    </div>
  
            
  </div>
</div>